---
- name: Check whether the docker socket exists
  ansible.builtin.stat:
    path: /var/run/docker.sock
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: ipaclient_postinstall_docker_socket
  tags: ipaclient-docker-group

- name: Make sure that the docker socket is owned by the IPA docker group
  block:
    - ansible.builtin.include_tasks: docker_group_ipa.yml
  when: ipaclient_postinstall_docker_socket['stat']['exists']
  tags: ipaclient-docker-group

- name: Change the default umask for user homes created by the pam_mkhomedir module.
  block:
    - ansible.builtin.include_tasks: pam_mkhomedir_umask.yml
  tags: ipaclient-homedir-permissions

- name: Make sure the sockets for activation sssd services are not blocked by sssd.conf
  block:
    - ansible.builtin.include_tasks: sssd_socket_activation.yml
  tags: ipaclient-sssd-socket-activation-fix
