---

- name: Include ipa services tasks
  block:
    - ansible.builtin.include_tasks: create_services.yml
  run_once: true
  tags:
    - ipa-services
    - ipa-settings

- name: Include ipa services tasks
  block:
    - ansible.builtin.include_tasks: ensure_general_config.yml
  run_once: true
  tags:
    - ipa-generalconfig
    - ipa-settings

- name: Include ipa hostgroups tasks
  block:
    - ansible.builtin.include_tasks: create_hostgroups.yml
  run_once: true
  tags:
    - ipa-hostgroups
    - ipa-settings

- name: Include ipa hbac rule tasks
  block:
    - ansible.builtin.include_tasks: create_hbacrules.yml
  run_once: true
  tags:
    - ipa-hbacrules
    - ipa-settings

- name: Include ipa rbac rule tasks
  block:
    - ansible.builtin.include_tasks: create_rbacrules.yml
  run_once: true
  tags:
    - ipa-rbacrules
    - ipa-settings

# FIXME: kerberos authentication needed to automatically create the automountmaps
# - name: include automountmaps tasks
#   block:
#     - ansible.builtin.include_tasks: create_automountmaps.yml
#   run_once: true
#   loop: "{{ ipa-automountmaps }}"
#   loop_control:
#     loop_var: mountmap
#   tags:
#     - ipa-automountmaps
#     - ipa-settings
