---
- name: Add the cgroup configuration file
  ansible.builtin.copy:
    src: cgroup.conf
    dest: /etc/slurm-llnl/cgroup.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - stop slurmctld
    - start slurmctld

- name: Add the main configuration file
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - stop slurmctld
    - start slurmctld

- name: Create the log directory
  ansible.builtin.file:
    path: "{{ slurm_log_dir }}"
    state: directory
    mode: "0755"
    owner: slurm
    group: slurm
